### ISSUE TITLE
Specify sources

### ISSUE THREAD

**Issue by yuvalpinter** [UniversalDependencies/UD_Ancient_Hebrew-PTNK#1]
Can you please write in the project description which biblical texts are included here? To me it looks like this is all of Genesis and Ruth, but it would be nice to know officially.

**Comment by mr-martian** [comment]
You are correct. Added to readme in [c50b68a](https://github.com/UniversalDependencies/UD_Ancient_Hebrew-PTNK/commit/c50b68af62e5adcaf30f6ef629492d9c54319c82).
